# https://goreleaser.com
version: 2
project_name: altmount

# Skip building binaries
builds:
  - skip: true

checksum:
  name_template: 'checksums-cli.txt'
  algorithm: sha512

changelog:
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge branch' 
# Docker - Optimized separate platform builds
dockers:
  - image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
    use: buildx
    dockerfile: ./docker/Dockerfile
    build_flag_templates:
      - --platform=linux/amd64
      - --cache-from=type=gha,scope=docker-amd64
      - --cache-to=type=gha,mode=max,scope=docker-amd64
      - --cache-from=type=registry,ref={{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:buildcache-amd64
      - --cache-to=type=registry,ref={{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:buildcache-amd64,mode=max
      - --cache-from=type=registry,ref={{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:buildcache-frontend
      - --build-arg=BUILDKIT_INLINE_CACHE=1
      - --metadata-file=/tmp/metadata-amd64.json
    extra_files:
      - docker
      - go.mod
      - go.sum
      - frontend
      - cmd
      - internal
      - pkg
  - image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-arm64'
    use: buildx
    goarch: arm64
    dockerfile: ./docker/Dockerfile
    build_flag_templates:
      - --platform=linux/arm64
      - --cache-from=type=gha,scope=docker-arm64
      - --cache-to=type=gha,mode=max,scope=docker-arm64
      - --cache-from=type=registry,ref={{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:buildcache-arm64
      - --cache-to=type=registry,ref={{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:buildcache-arm64,mode=max
      - --cache-from=type=registry,ref={{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:buildcache-frontend
      - --cache-to=type=registry,ref={{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:buildcache-frontend,mode=max
      - --build-arg=BUILDKIT_INLINE_CACHE=1
      - --metadata-file=/tmp/metadata-arm64.json
    extra_files:
      - docker
      - go.mod
      - go.sum
      - frontend
      - cmd
      - internal
      - pkg

docker_manifests:
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-arm64'
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Major }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-arm64'
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Major }}.{{ .Minor }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-arm64'
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ if .IsSnapshot }}{{ .Branch }}{{ else }}latest{{ end }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-amd64'
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Version }}-arm64'