# AltMount Configuration Sample
# Copy this file to config.yaml and modify for your setup

# WebDAV server configuration
webdav:
  port: 8080
  user: "usenet"
  password: "usenet"
  debug: false

# API server configuration
api:
  enabled: true
  prefix: "/api"

# Database configuration
database:
  path: "/Users/javi/mio/altmount/example/altmount.db"

# Mount path for the virtual filesystem
mount_path: "/mnt/altmount"

# Directory containing NZB files to process
nzb_dir: "/Users/javi/mio/altmount/example/nzbs"

# RClone encryption settings (optional)
rclone:
  password: "Primax;1992"
  salt: "Primax$1992"

# Worker configuration
workers:
  download: 9      # Number of download workers
  processor: 10      # Number of queue processor workers

# Global debug mode
debug: true

metadata:
  root_path: "/Users/javi/mio/altmount/example/metadata"   # Directory to store metadata files (required)
  cache_size: 1000          # Number of metadata entries to cache in memory

# NNTP Providers Configuration
# Configure multiple providers for redundancy and load balancing
providers:
  # Primary provider with SSL
  - name: "newsgroup"
    host: "news.newsgroup.ninja"    # Replace with your provider's SSL hostname
    port: 80
    username: "laris11"        # Replace with your username
    password: "7abdJ!PhuXyFxz7"        # Replace with your password
    max_connections: 9
    tls: true
    insecure_tls: false
    
  # Secondary provider (optional)
  # - name: "secondary-provider"
  #   host: "news.otherprovider.com"
  #   port: 563
  #   username: "other_username"
  #   password: "other_password"
  #   max_connections: 15
  #   tls: true
  #   insecure_tls: false

# Configuration Notes:
# 
# 1. NNTP Providers:
#    - At least one provider must be configured
#    - Multiple providers provide redundancy and load balancing
#    - SSL/TLS is recommended when available (port 563)
#    - Standard unencrypted connections typically use port 119
#
# 2. Max Connections:
#    - Set based on your provider's limits
#    - More connections = faster downloads but higher resource usage
#    - Typical range: 10-50 connections per provider
#
# 3. Workers:
#    - Download workers: Number of concurrent download threads
#    - Processor workers: Number of NZB processing threads
#    - Adjust based on your system resources and provider limits
#
# 4. Paths:
#    - Use absolute paths for production deployments
#    - Relative paths are relative to the working directory
#    - Ensure the application has read/write access to all paths
#
# 5. Security:
#    - Store credentials securely
#    - Consider using environment variables for sensitive data
#    - Use strong passwords for WebDAV authentication